# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "564256729c36fe4740cf7a84befaa490"
name = "ema-interactive-assistant"
handle = "ema-interactive-assistant"

# 🚀 SHOPIFY APP URL - Deploy ema-interactive-assistant to Vercel (recommended)
# This is where your Shopify app frontend lives (the admin interface)
application_url = "https://ema-interactive-assistant-shopify-a.vercel.app"  # e.g., https://ema-interactive-assistant.vercel.app

embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
# 🚀 SHOPIFY APP REDIRECT URLs - Same as application_url above
redirect_urls = [
  "https://ema-interactive-assistant-shopify-a.vercel.app/auth/callback", 
  "https://ema-interactive-assistant-shopify-a.vercel.app/auth/shopify/callback", 
  "https://ema-interactive-assistant-shopify-a.vercel.app/api/auth/callback"
]

[pos]
embedded = false
