name = "voice-chat-widget"
type = "theme"

[extensions.theme]

[[extensions.theme.blocks]]
type = "app_embed"
name = "Voice Chat Widget"
target = "body"

[[extensions.theme.blocks]]
type = "star_rating"
name = "Star Rating"
target = "section"

